[2025-04-12T10:18:36.915+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-12T10:18:36.970+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_ingestion_dag.ingest scheduled__2025-04-12T09:00:00+00:00 [queued]>
[2025-04-12T10:18:36.988+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_ingestion_dag.ingest scheduled__2025-04-12T09:00:00+00:00 [queued]>
[2025-04-12T10:18:36.989+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-12T10:18:37.000+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest> on 2025-04-12 09:00:00+00:00
[2025-04-12T10:18:37.013+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'air_ingestion_dag', 'ingest', 'scheduled__2025-04-12T09:00:00+00:00', '--job-id', '772', '--raw', '--subdir', 'DAGS_FOLDER/air_ingestion_dag.py', '--cfg-path', '/tmp/tmp20ygjt36']
[2025-04-12T10:18:37.017+0000] {standard_task_runner.py:105} INFO - Job 772: Subtask ingest
[2025-04-12T10:18:37.016+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=207) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-12T10:18:37.021+0000] {standard_task_runner.py:72} INFO - Started process 224 to run task
[2025-04-12T10:18:37.107+0000] {task_command.py:467} INFO - Running <TaskInstance: air_ingestion_dag.ingest scheduled__2025-04-12T09:00:00+00:00 [running]> on host e1fcb75fb946
[2025-04-12T10:18:37.216+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='beni' AIRFLOW_CTX_DAG_ID='air_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T09:00:00+00:00'
[2025-04-12T10:18:37.218+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-12T10:18:37.220+0000] {air_ingestion_dag.py:30} INFO - üìÖ Fetching UBA data for MEZ day: 2025-04-12
[2025-04-12T10:18:37.230+0000] {logging_mixin.py:190} INFO - ‚ùå API Error: HTTPSConnectionPool(host='umweltbundesamt.api.proxy.bund.dev', port=443): Max retries exceeded with url: /api/air_data/v3/airquality/json?station=443&date_from=2025-04-12&time_from=6&date_to=2025-04-12&time_to=23&index=code&lang=en (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff741506e0>: Failed to resolve 'umweltbundesamt.api.proxy.bund.dev' ([Errno -2] Name or service not known)"))
[2025-04-12T10:18:37.230+0000] {air_ingestion_dag.py:40} INFO - üì¶ Parsed 0 entries
[2025-04-12T10:18:37.231+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-12T10:18:37.242+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-12T10:18:37.243+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=air_ingestion_dag, task_id=ingest, run_id=scheduled__2025-04-12T09:00:00+00:00, execution_date=20250412T090000, start_date=20250412T101836, end_date=20250412T101837
[2025-04-12T10:18:37.289+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-12T10:18:37.303+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-12T10:18:37.304+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
