[2025-04-06T07:50:00.093+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T07:50:00.119+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_ingestion_dag.ingest scheduled__2025-04-06T03:00:00+00:00 [queued]>
[2025-04-06T07:50:00.138+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_ingestion_dag.ingest scheduled__2025-04-06T03:00:00+00:00 [queued]>
[2025-04-06T07:50:00.138+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-06T07:50:00.147+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest> on 2025-04-06 03:00:00+00:00
[2025-04-06T07:50:00.153+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=170) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-06T07:50:00.155+0000] {standard_task_runner.py:72} INFO - Started process 173 to run task
[2025-04-06T07:50:00.159+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'air_ingestion_dag', 'ingest', 'scheduled__2025-04-06T03:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/air_ingestion_dag.py', '--cfg-path', '/tmp/tmpyazls6n9']
[2025-04-06T07:50:00.166+0000] {standard_task_runner.py:105} INFO - Job 153: Subtask ingest
[2025-04-06T07:50:00.240+0000] {task_command.py:467} INFO - Running <TaskInstance: air_ingestion_dag.ingest scheduled__2025-04-06T03:00:00+00:00 [running]> on host 242fb041fbeb
[2025-04-06T07:50:00.345+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='beni' AIRFLOW_CTX_DAG_ID='air_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-06T03:00:00+00:00'
[2025-04-06T07:50:00.347+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T07:50:00.377+0000] {logging_mixin.py:190} INFO - ‚ùå API Error: HTTPSConnectionPool(host='umweltbundesamt.api.proxy.bund.dev', port=443): Max retries exceeded with url: /api/air_data/v3/airquality/json?station=443&date_from=2025-04-06&time_from=6&date_to=2025-04-06&time_to=18&index=code&lang=en (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffffa573db50>: Failed to resolve 'umweltbundesamt.api.proxy.bund.dev' ([Errno -2] Name or service not known)"))
[2025-04-06T07:50:00.378+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-06T07:50:00.404+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T07:50:00.405+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=air_ingestion_dag, task_id=ingest, run_id=scheduled__2025-04-06T03:00:00+00:00, execution_date=20250406T030000, start_date=20250406T075000, end_date=20250406T075000
[2025-04-06T07:50:00.462+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-06T07:50:00.488+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T07:50:00.493+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
