[2025-04-09T14:54:26.647+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T14:54:26.670+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_forecast_ingestion_dag.ingest manual__2025-04-09T14:54:25.471782+00:00 [queued]>
[2025-04-09T14:54:26.680+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_forecast_ingestion_dag.ingest manual__2025-04-09T14:54:25.471782+00:00 [queued]>
[2025-04-09T14:54:26.680+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-09T14:54:26.687+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest> on 2025-04-09 14:54:25.471782+00:00
[2025-04-09T14:54:26.689+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=93) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T14:54:26.690+0000] {standard_task_runner.py:72} INFO - Started process 94 to run task
[2025-04-09T14:54:26.691+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_forecast_ingestion_dag', 'ingest', 'manual__2025-04-09T14:54:25.471782+00:00', '--job-id', '503', '--raw', '--subdir', 'DAGS_FOLDER/weather_forecast_ingestion_dag.py', '--cfg-path', '/tmp/tmpoo3eif4p']
[2025-04-09T14:54:26.693+0000] {standard_task_runner.py:105} INFO - Job 503: Subtask ingest
[2025-04-09T14:54:26.723+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_forecast_ingestion_dag.ingest manual__2025-04-09T14:54:25.471782+00:00 [running]> on host 98acdd3c69ae
[2025-04-09T14:54:26.769+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='beni' AIRFLOW_CTX_DAG_ID='weather_forecast_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T14:54:25.471782+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T14:54:25.471782+00:00'
[2025-04-09T14:54:26.769+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T14:54:26.771+0000] {weather_forecast_ingestion_dag.py:35} INFO - üå§Ô∏è Fetching forecast for date: 2025-04-09
[2025-04-09T14:54:26.911+0000] {weather_forecast_ingestion_dag.py:41} WARNING - ‚ö†Ô∏è No forecast entries found.
[2025-04-09T14:54:26.912+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-09T14:54:26.925+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T14:54:26.925+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_forecast_ingestion_dag, task_id=ingest, run_id=manual__2025-04-09T14:54:25.471782+00:00, execution_date=20250409T145425, start_date=20250409T145426, end_date=20250409T145426
[2025-04-09T14:54:26.956+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-09T14:54:26.966+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T14:54:26.967+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
